spring:
  application:
    name: BOOK-SERVICE
  datasource:
    url: jdbc:h2:~/book
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: 'true'
      fileSizeThreshold: 2KB #after the fileSizeThreshold size file will be saved
      maxFileSize: 15MB
      maxRequestSize: 15MB
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
